config/routes.rb
NlpSampleApp::Application.routes.draw do

  devise_for :users
  resources :books do
    get 'search', on: :collection
    get 'autocomplete', on: :collection
  end

  root 'home#index'

  namespace :rails_nlp do
    resources :keywords
  end



end

app/models/book.rb
class Book < ActiveRecord::Base
  include PgSearch
  include RailsNlp
  pg_search_scope :search_title, against: :title
  pg_search_scope :search_content, against: :content
  pg_search_scope :search_title_and_content, against: [:title, :content]
  pg_search_scope :search_metaphones, associated_against: {
    :keywords => :metaphone
  }
  pg_search_scope :search_stems, associated_against: {
    :keywords => :stem
  }

  pg_search_scope :autocomplete, against: :title, using: :trigram
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def search
    search_scope = params[:search] || Searcher::TITLE
    @result_set = Searcher.search(query: params[:query], scope: search_scope)
    @result_set.page = params[:page]
  end

  def autocomplete
    render json: Book.autocomplete(params[:query]).limit(10).to_json(only: [:title, :id])
  end

  # GET /books
  # GET /books.json
  def index
    @books = Book.all.page(params[:page]).per(5)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/rails_nlp/keywords_controller.rb
module RailsNlp
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = RailsNlp::Keyword.page(params[:page]).per(100)
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = RailsNlp::Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = RailsNlp::Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'RailsNlp::Keyword was successfully created.' }
        format.json { render action: 'show', status: :created, location: @keyword }
      else
        format.html { render action: 'new' }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = RailsNlp::Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:name, :metaphone, :stem)
    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<%= paginate @books %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.content[0..1000] if book.content %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<div class="results">
    <div class="large-12 columns ">
      <div class="row">
        <div class="large-9 columns">
          <h2 class="search-query search-results-count">
            <%= pluralize(@result_set.size, 'result') + " for \"#{@result_set.query}\""%>
          </h2>
          <% if (!@result_set.query.correct? && @result_set.query.corrected != @result_set.query.to_s) %>
            <p>Did you mean <em><span id=search_suggestion>
              <%= link_to(@result_set.query.corrected, search_books_path(query: @result_set.query.corrected, search: @result_set.scope)) %>
            </span></em>?</p>
        <% end %>
          <dl id="query-expanded" class="">
            <dt>Search scope</dt>
            <dd><%= @result_set.scope.gsub(/_/,' ').titlecase %></dd>
            <dt>Stopwords removed</dt>
            <dd><%= @result_set.query.keywords %></dd>
            <dt>Metaphone conversion</dt>
            <dd><%= @result_set.query.metaphones %></dd>
            <dt>Stem conversion</dt>
            <dd><%= @result_set.query.stems %></dd>
          </dl>
        </div>
      </div>
      <%= paginate @result_set.results %>
      <div class="search-results">
        <% @result_set.results.each do |book| %>
        <div class="row ">
          <div class="large-2 columns">
            <a href="#"> <span> </span><img src="http://placehold.it/150x200&text=book cover" alt="book cover" class=" thumbnail"></a>
          </div>
          <div class="large-10 columns">
            <div class="row">
              <div class=" large-9 columns">
                <h5 class="book-title"><%= book.title %></h5>
                <p><a href="#"> Info</a> | <a href="#">Buy this book</a></p>
              </div>
              <div class=" large-3 columns">
              <%= link_to  book_path(book), class: "button expand medium" do %>
                <span>Open Book</span>
              <% end %>
              </div>
              <div class="row">
                <div class=" large-12 columns">
                  <ul class="large-block-grid-2">
                    <div class="large-9 columns">
                      <p class="book-content">
                      <%= book.content[0..1000] %>
                      </p>
                    </div>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
      <% end %>
      </div>
      <%= paginate @result_set.results %>
    </div>
  </div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @book.content %>
</p>

<h3>Keywords</h3>

<% @freq = @book.keywords.order('wordcounts.count DESC').joins(:wordcounts).pluck(:name).each_with_object(Hash.new(0)) { |w, counts| counts[w] +=1 } %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
    </tr>
  </thead>

  <tbody>
    <% @freq.each do |word, count| %>
      <tr>
        <td><%= word %></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "RailsNlp", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon">
      <a href="#"><span>Menu</span></a>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="left">
      <li><%= link_to "Search", root_path %></li>
      <li><%= link_to "Books", books_path %></li>
      <li><%= link_to "Keywords", rails_nlp_keywords_path %></li>
    </ul>
  </section>
</nav>

app/views/home/index.html.erb
<div class="row search">
  <div class=" small-12 columns">
    <div class="row collapse">
      <h1>Science Fiction Bookshelf</h1>
      <%= render partial: "search/form" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "RailsNlp: Science Fiction Bookshelf" %></title>



    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body data-no-turbolink>

    <div class="row">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div class="sticky">
      <%= render partial: 'home/nav' %>
    </div>

    <div class="row">
      <%= yield %>
    <div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/rails_nlp/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :metaphone %><br>
    <%= f.text_field :metaphone %>
  </div>
  <div class="field">
    <%= f.label :stem %><br>
    <%= f.text_field :stem %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rails_nlp/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/rails_nlp/keywords/index.html.erb
<h1>Listing keywords</h1>

<%= paginate @keywords %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Metaphone</th>
      <th>Stem</th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.name %></td>
        <td><%= keyword.metaphone %></td>
        <td><%= keyword.stem %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rails_nlp/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/rails_nlp/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @keyword.name %>
</p>

<p>
  <strong>Metaphone:</strong>
  <%= @keyword.metaphone %>
</p>

<p>
  <strong>Stem:</strong>
  <%= @keyword.stem %>
</p>

<%= link_to 'Back', rails_nlp_keywords_path %>

app/views/search/_form.html.erb
<!-- Search field -->
<div class="small-8 large-10 columns ">
  <%= form_tag(search_books_path, method: :get) do %>
    <%= label_tag(:query, "Search for:") %>
    <%= text_field_tag(:query, nil, id: "book_search") %>
    <%= label_tag(:search, "Search on:") %><br />
    <%= radio_button_tag('search', 'title', true) %>
    <%= label_tag(:search, "Title", value: 'title') %>
    <%= radio_button_tag('search', 'content') %>
    <%= label_tag(:search, "Content", value: 'content') %>
    <%= radio_button_tag('search', 'title_and_content') %>
    <%= label_tag(:search, "Title and content", value: 'title_and_content') %>
    <%= radio_button_tag('search', 'metaphones') %>
    <%= label_tag(:search, "Metaphones", value: 'metaphones') %>
    <%= radio_button_tag('search', 'stems') %>
    <%= label_tag(:search, "Stems", value: 'stems') %>
    <%= submit_tag("Search") %>
  <% end %>
</div>

app/views/search/index.html.erb
<div class="row results">
    <div class="large-12 columns ">
      <div class="row">
        <div class="large-9 columns">
          <p> Search Results for "Cat Books: 123</p>
        </div>
        <div class=" large-3 columns ">
          <select name="sortOptions">
            <option value="sortby">Sort By</option>
            <option value="cats">Cats</option>
            <option value="title">Title</option>
            <option value="author">Author</option>
            <option value="mrecats">More Cats</option>
          </select>
        </div>
      </div>
      <div class="search-results">
        <div class="row ">
          <div class="large-2 columns">
            <a href="#"> <span> </span><img src="http://placehold.it/150x200&text=book cover" alt="book cover" class=" thumbnail"></a>
          </div>
          <div class="large-10 columns">
            <div class="row">
              <div class=" large-9 columns">
                <h5><a href="#">Do cats hear with their feet? : where cats come from, what we know about them, and what they think about us </a></h5>
                <p><a href="#"> Info</a> | <a href="#">Buy this book</a></p>
              </div>
              <div class=" large-3 columns">
                <a href="#"  class="button  expand medium"><span>Open Book</span> </a>
                <a href="#"  class="button  expand medium"><span>Add to List</span></a> 
              </div>
              <div class="row">
                <div class=" large-12 columns">
                  <ul class="large-block-grid-2">
                    <li>
                      <ul>
                        <li><strong>Author: </strong>John Doe</li>
                        <li><strong>Published:</strong> 2008</li>
                        <li><strong>More info:</strong> Lorem ipsum</li>
                        <li><strong>More cat stuff: </strong> cats cats cats</li>
                      </ul>
                    </li>
                    <li>
                      <ul>
                        <li><strong>Wow cats:</strong> so wow</li>
                        <li><strong>Lorem cats:</strong> ipsum kitty</li>
                        <li><strong>Series:</strong> all the cats</li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
        <div class="row ">
          <div class="large-2 columns">
            <a href="#"> <span> </span><img src="http://placehold.it/150x200&text=book cover" alt="book cover" class=" thumbnail"></a>
          </div>
          <div class="large-10 columns">
            <div class="row">
              <div class=" large-9 columns">
                <h5><a href="#">Do cats hear with their feet? : where cats come from, what we know about them, and what they think about us </a></h5>
                <p><a href="#"> Info</a> | <a href="#">Buy this book</a></p>
              </div>
              <div class=" large-3 columns">
                <a href="#"  class="button  expand medium"><span>Open Book</span> </a>
                <a href="#"  class="button  expand medium"><span>Add to List</span></a> 
              </div>
              <div class="row">
                <div class=" large-12 columns">
                  <ul class="large-block-grid-2">
                    <li>
                      <ul>
                        <li><strong>Author: </strong>John Doe</li>
                        <li><strong>Published:</strong> 2008</li>
                        <li><strong>More info:</strong> Lorem ipsum</li>
                        <li><strong>More cat stuff: </strong> cats cats cats</li>
                      </ul>
                    </li>
                    <li>
                      <ul>
                        <li><strong>Wow cats:</strong> so wow</li>
                        <li><strong>Lorem cats:</strong> ipsum kitty</li>
                        <li><strong>Series:</strong> all the cats</li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
        <div class="row ">
          <div class="large-2 columns">
            <a href="#"> <span> </span><img src="http://placehold.it/150x200&text=book cover" alt="book cover" class=" thumbnail"></a>
          </div>
          <div class="large-10 columns">
            <div class="row">
              <div class=" large-9 columns">
                <h5><a href="#">Do cats hear with their feet? : where cats come from, what we know about them, and what they think about us </a></h5>
                <p><a href="#"> Info</a> | <a href="#">Buy this book</a></p>
              </div>
              <div class=" large-3 columns">
                <a href="#"  class="button  expand medium"><span>Open Book</span> </a>
                <a href="#"  class="button  expand medium"><span>Add to List</span></a> 
              </div>
              <div class="row">
                <div class=" large-12 columns">
                  <ul class="large-block-grid-2">
                    <li>
                      <ul>
                        <li><strong>Author: </strong>John Doe</li>
                        <li><strong>Published:</strong> 2008</li>
                        <li><strong>More info:</strong> Lorem ipsum</li>
                        <li><strong>More cat stuff: </strong> cats cats cats</li>
                      </ul>
                    </li>
                    <li>
                      <ul>
                        <li><strong>Wow cats:</strong> so wow</li>
                        <li><strong>Lorem cats:</strong> ipsum kitty</li>
                        <li><strong>Series:</strong> all the cats</li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
        <div class="row ">
          <div class="large-2 columns">
            <a href="#"> <span> </span><img src="http://placehold.it/150x200&text=book cover" alt="book cover" class=" thumbnail"></a>
          </div>
          <div class="large-10 columns">
            <div class="row">
              <div class=" large-9 columns">
                <h5><a href="#">Do cats hear with their feet? : where cats come from, what we know about them, and what they think about us </a></h5>
                <p><a href="#"> Info</a> | <a href="#">Buy this book</a></p>
              </div>
              <div class=" large-3 columns">
                <a href="#"  class="button  expand medium"><span>Open Book</span> </a>
                <a href="#"  class="button  expand medium"><span>Add to List</span></a> 
              </div>
              <div class="row">
                <div class=" large-12 columns">
                  <ul class="large-block-grid-2">
                    <li>
                      <ul>
                        <li><strong>Author: </strong>John Doe</li>
                        <li><strong>Published:</strong> 2008</li>
                        <li><strong>More info:</strong> Lorem ipsum</li>
                        <li><strong>More cat stuff: </strong> cats cats cats</li>
                      </ul>
                    </li>
                    <li>
                      <ul>
                        <li><strong>Wow cats:</strong> so wow</li>
                        <li><strong>Lorem cats:</strong> ipsum kitty</li>
                        <li><strong>Series:</strong> all the cats</li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <hr>
        </div>
      </div>
      <a href="#" class="button right"> show more results &raquo;</a>
    </div>
  </div>